#!/usr/bin/env bash
# netlify-build.sh — runs during Netlify build
# Injects firebase-config.js from Netlify environment variables
# and updates the Service Worker cache version with build timestamp.
set -e

echo "=== Netlify Build Script ==="

# ── 1. Inject Firebase config ─────────────────────────────────────────────────
# Variables are set in: Netlify → Site → Site configuration → Environment variables
if [ -n "$FIREBASE_API_KEY" ]; then
  echo "✓ Injecting firebase-config.js from environment variables..."
  cat > firebase-config.js << JSEOF
// Auto-generated by netlify-build.sh — DO NOT COMMIT
const FIREBASE_CONFIG = {
  apiKey:            "${FIREBASE_API_KEY}",
  authDomain:        "${FIREBASE_AUTH_DOMAIN}",
  projectId:         "${FIREBASE_PROJECT_ID}",
  storageBucket:     "${FIREBASE_STORAGE_BUCKET}",
  messagingSenderId: "${FIREBASE_MESSAGING_SENDER_ID}",
  appId:             "${FIREBASE_APP_ID}",
  orgId:             "${FIREBASE_ORG_ID}",
  teamEmail:         "${FIREBASE_TEAM_EMAIL}",
  teamPassword:      "${FIREBASE_TEAM_PASSWORD}",
};
JSEOF
  echo "✓ firebase-config.js created"
else
  echo "⚠ FIREBASE_API_KEY not set — skipping firebase-config.js injection"
  echo "  (App will run in local-only mode)"
fi

# ── 2. Update Service Worker cache version with build timestamp ───────────────
BUILD_TS=$(date -u +%Y%m%dT%H%M%S)
if [ -f "sw.js" ]; then
  sed -i "s/const CACHE_VERSION  = .*/const CACHE_VERSION  = '${BUILD_TS}';/" sw.js
  echo "✓ SW cache version updated: ${BUILD_TS}"
fi

echo "=== Build complete ==="
